language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
gemfile:
  - gemfiles/rails-5-0.gemfile
  - gemfiles/rails-5-1.gemfile
  - gemfiles/rails-5-2.gemfile
  - gemfiles/rails-6-0.gemfile
env:
  - DB=mysql
  - DB=pgsql
services:
  - mysql
  - postgresql
before_install:
  - mysql -e 'CREATE DATABASE persistent_hash_test;'
before_script:
  - psql -c 'CREATE DATABASE persistent_hash_test;' -U postgres
script:
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake spec
