default: &default
  username: <%= ENV['DB_USERNAME'] || 'root' %>
<% if ENV['DB'] == 'mysql' || !ENV['DB'] %>
  password:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
<% elsif ENV['DB'] == 'pgsql' %>
  adapter: postgresql
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
<%
  else
    raise "unknown DB value '#{ENV['DB']}'"
  end
%>

development:
  <<: *default
  database: persistent_hash_development

test:
  <<: *default
  database: persistent_hash_test
