default: &default
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password:
<% if ENV['DB'] == 'mysql' || !ENV['DB'] %>
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
<% elsif ENV['DB'] == 'pgsql' %>
  adapter: postgresql
  host: localhost
  port: 5432
<%
  else
    raise "unknown DB value '#{ENV['DB']}'"
  end
%>

development:
  <<: *default
  database: persistent_hash_development

test:
  <<: *default
  database: persistent_hash_test
