default: &default
  password: <%= ENV['DB_PASSWORD'] %>
<% if !ENV['DB'] %>
  adapter: mysql2
  username: root'
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
<% elsif ENV['DB'] == 'mysql' %>
  adapter: mysql2
  host: 127.0.0.1
  port: 3306
  username: <%= ENV['DB_USERNAME'] %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
<% elsif ENV['DB'] == 'pgsql' %>
  adapter: postgresql
  host: localhost
  port: 5432
  user: <%= ENV['DB_USERNAME'] %>
<%
  else
    raise "unknown DB value '#{ENV['DB']}'"
  end
%>

development:
  <<: *default
  database: persistent_hash_development

test:
  <<: *default
  database: persistent_hash_test
