# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: rspec

on:
  push:
    branches: '**'

env:
  # configures database.yml in dummy app
  DB: pgsql
  DB_USERNAME: test
  # https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
  # use localhost for the host here because we are running the job on the VM.
  # If we were running the job on in a container this would be postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432 # ${{ services.postgres.ports[5432] }} # get randomly assigned published port
  POSTGRES_PASSWORD: password # copypasta. ${{ job.services.postgres.env.POSTGRES_PASSWORD }}
  RAILS_ENV: test

# next: 1 job per database. re-use strategy and steps.
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: test
          POSTGRES_DB: persistent_hash_test
          # password cannot be blank?
          # https://dev.to/lxxxvi/til-using-postgres-in-github-actions-3j
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports: ["5432:5432"]
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.5', '2.6', '2.7', '3.0', '3.1']
        gemfile: ['gemfiles/rails-5-2.gemfile', 'gemfiles/rails-6-0.gemfile']
        exclude:
          # rails 5.2 doesnt work with ruby 3
          - gemfile: 'gemfiles/rails-5-2.gemfile'
            ruby: '3.0'
          - gemfile: 'gemfiles/rails-5-2.gemfile'
            ruby: '3.1'

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install --gemfile=${{ matrix.gemfile }}
      - name: Setup test database
        run: |
          bundle exec --gemfile=${{ matrix.gemfile }} rails db:schema:load --trace
      - name: Run tests
        run: |
          bundle exec --gemfile=${{ matrix.gemfile }} rake spec --trace
